---
  - hosts: all
    remote_user: ansible
    become: yes
    tasks:
      - name: Install docker
        ansible.builtin.yum:
          name: docker
          lock_timeout: 180
      - name: Start docker service
        ansible.builtin.systemd:
          name: docker
          state: started
      - name: Enable docker service
        ansible.builtin.systemd:
          name: docker
          enabled: true
      - name: Create docker group
        ansible.builtin.group:
          name: docker
          state: present
          gid: 1750
      - name: Install Git
        ansible.builtin.yum:
          name: git
          lock_timeout: 180    
      - name: Install CRI
        ansible.builtin.shell: |
          git clone https://github.com/Mirantis/cri-dockerd.git
          cd cri-dockerd
          make cri-dockerd
          cd cri-dockerd
          mkdir -p /usr/local/bin
          install -o root -g root -m 0755 cri-dockerd /usr/local/bin/cri-dockerd
          install packaging/systemd/* /etc/systemd/system
          sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service
      - name: Daemon reload
        ansible.builtin.systemd:
          daemon_reload: true
      - name: Enable docker CRI service
        ansible.builtin.systemd:
          name: cri-docker.service
          enabled: true
      - name: Enable docker CRI socket
        ansible.builtin.systemd:
          name: cri-docker.socket
          enabled: true    
      - name: Install kubeadm, kubectl & kubelet
        ansible.builtin.shell: |
          cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kubelet kubeadm kubectl
          EOF
          sudo setenforce 0
          sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
          sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
          sudo systemctl enable --now kubelet