---
  - hosts: all
    remote_user: ansible
    become: yes
    tasks:
      - name: Install yum utils
        ansible.builtin.yum:
          name: yum-utils
          state: latest
          lock_timeout: 180
      - name: Add docker-ce repo
        ansible.builtin.shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 
      - name: Install docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin
        ansible.builtin.yum:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-buildx-plugin
            - docker-compose-plugin
          lock_timeout: 180
          state: present        
      - name: Start docker service
        ansible.builtin.systemd:
          name: docker
          state: started
      - name: Enable docker service
        ansible.builtin.systemd:
          name: docker
          enabled: true
      - name: Create docker group
        ansible.builtin.group:
          name: docker
          state: present
          gid: 1750
      - name: Install wget
        ansible.builtin.yum:
          name: wget
          lock_timeout: 180
          state: present
      - name: Upgrade containerd
        ansible.builtin.shell: |
          wget https://github.com/containerd/containerd/releases/download/v1.6.12/containerd-1.6.12-linux-amd64.tar.gz
          tar xvf containerd-1.6.12-linux-amd64.tar.gz
          systemctl stop containerd
          cd bin
          cp * /usr/bin/
          mv /etc/containerd/config.tom ~/
          systemctl start containerd
      - name: Install Git
        ansible.builtin.yum:
          name: git
          lock_timeout: 180
          state: present        
      - name: Install kubeadm, kubectl & kubelet
        ansible.builtin.shell: |
          cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kubelet kubeadm kubectl
          EOF
          sudo setenforce 0
          sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
          sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
          sudo systemctl enable --now kubelet